default:
  SECRET_KEY: {{random_ascii_string(32)}}
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: {{cookiecutter.module_name}}
      USER: postgres
      PASSWORD: {{cookiecutter.db_password}}
      HOST: db
      PORT: 5432
