default:
  SECRET_KEY: GoË†gMhrCcQJmbw2o?AwrQqV53.(0{7!x
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: super_pizzaria
      USER: postgres
      PASSWORD: q2Tq9^b_q*WwrHcW
      HOST: localhost
      PORT: 5432